const starterSkills=[{name:'File Retrieval',job:'Locate and return the correct file or information source efficiently.',tags:['Files','Retrieval']},{name:'Task Documentation',job:'Turn completed work into clear, reusable task documentation.',tags:['Docs','Workflow']},{name:'File Organization',job:'Organize files using consistent naming, folders, and handling rules.',tags:['Files','Organization']}];
const grid=document.querySelector('#skillGrid');
let activeIndex=0;
function renderSkills(list=starterSkills){grid.innerHTML='';list.forEach((s)=>{const originalIndex=starterSkills.indexOf(s);grid.insertAdjacentHTML('beforeend',`<article class="card skill-card" tabindex="0" data-index="${originalIndex}"><p class="eyebrow">SKILL</p><h2>${s.name}</h2><p>${s.job}</p><div>${s.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><button class="card-open" data-index="${originalIndex}">View Details</button></article>`)});bindCards();}
function bindCards(){document.querySelectorAll('.skill-card').forEach(card=>{card.onclick=()=>selectSkill(Number(card.dataset.index));card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectSkill(Number(card.dataset.index));}}});document.querySelectorAll('.card-open').forEach(btn=>btn.onclick=e=>{e.stopPropagation();selectSkill(Number(btn.dataset.index));});}
function selectSkill(index){activeIndex=(index+starterSkills.length)%starterSkills.length;const s=starterSkills[activeIndex];document.querySelectorAll('.skill-card').forEach(c=>c.classList.toggle('selected',Number(c.dataset.index)===activeIndex));document.querySelector('#detailName').textContent=s.name;document.querySelector('#detailJob').textContent=s.job;document.querySelector('#detailTags').innerHTML=s.tags.map(t=>`<span class="tag">${t}</span>`).join('');}
renderSkills();selectSkill(0);
document.querySelector('#prevSkill').onclick=()=>selectSkill(activeIndex-1);document.querySelector('#nextSkill').onclick=()=>selectSkill(activeIndex+1);
document.querySelector('#skillSearch').oninput=e=>{const q=e.target.value.trim().toLowerCase();renderSkills(starterSkills.filter(s=>[s.name,s.job,...s.tags].join(' ').toLowerCase().includes(q)));};
document.querySelector('#copySkill').onclick=async()=>{const s=starterSkills[activeIndex];const text=`${s.name}\n\nPurpose: ${s.job}\nTags: ${s.tags.join(', ')}`;await navigator.clipboard.writeText(text);document.querySelector('#copySkill').textContent='Copied ✓';setTimeout(()=>document.querySelector('#copySkill').textContent='Copy',1200);};
document.querySelector('#downloadSkill').onclick=()=>{const s=starterSkills[activeIndex];const md=`# ${s.name}\n\n## Purpose\n${s.job}\n\n## Tags\n${s.tags.map(t=>`- ${t}`).join('\n')}\n`;const blob=new Blob([md],{type:'text/markdown'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=s.name.toLowerCase().replace(/\s+/g,'-')+'.md';a.click();URL.revokeObjectURL(a.href);};
document.querySelector('#integrateSkill').onclick=()=>alert(`Ready to assign “${starterSkills[activeIndex].name}” to an AI agent or workflow.`);
document.querySelector('#importSkill').onclick=()=>alert('Skill Import is ready for the package-validation workflow.');
document.querySelectorAll('button.nav[data-view]').forEach(btn=>btn.onclick=()=>show(btn.dataset.view,btn));
function show(id,btn){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));document.querySelector('#'+id).classList.add('active-view');document.querySelectorAll('.nav').forEach(n=>n.classList.remove('active'));btn.classList.add('active');document.querySelector('#pageTitle').textContent=id==='validator'?'Validator':'Skill Library';}
document.querySelector('#rules').innerHTML=['One Skill = One Job','Ground claims in supplied sources','Required tools/access are explicit','Human approval protects destructive/external actions','Workflow is executable by another AI','Output format is defined','Source grounding is preserved','Canonical skill stays platform-neutral'].map(x=>`<div class="rule"><span>${x}</span><b>Required</b></div>`).join('');
if(location.hash==='#validator'){show('validator',document.querySelector('[data-view="validator"]'));}